# Custom Language File for Launcher Customizer

[ejs.app]
title = "Sigmacraft Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/nrXgRrAkns"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR SIGMACRAFT"
welcomeDescription = "Notre mission est de réunir les élèves de l'école sur un serveur Minecraft qui aura pour objectif d'évoluer dans le temps."
welcomeDescCTA = "Vous n'êtes qu'à quelques clics de Sigmacraft."
